version: "3.7"

services:
  database:
    image: postgres
    container_name: db_rentalx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=db_rentalx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - ./src:/usr/app/src
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
